#!/usr/bin/env python

# NOTICE... this file is generated by tk_happy.
# Any code or comments added by the user must be in designated areas ONLY.
# User additions will be lost if they are placed in code-generated areas.


#    I like extra spaces inside parens and sometimes camelCase
# pylint: disable=C0326
# pylint: disable=C0103

# pylint: disable=R0902, R0915


"""
hatch_tkDialog is a GUI interface to create a Hatch object from
hatch_supt and to then create a skeleton python project.
"""

# tk_happy generated code. DO NOT EDIT THE FOLLOWING. section "imports"
#from Tkinter import *
from Tkinter import Frame, LabelFrame, Button, Entry, StringVar, Label,\
                    Radiobutton, W, Scrollbar, VERTICAL, Text, RIGHT, Y,\
                    LEFT, BOTH, DISABLED, END, NORMAL, Tk, OptionMenu
# >>>>>>insert any user code below this comment for section "imports"
# Place any user import statements here
import tkFileDialog
import tkMessageBox
import tkFont
import os
from hatch_supt import Hatch, DEV_STATUS_OPTIONS


# Man this is ugly... It's only used during development (prior to running
#   setup.py install) After installed, the pyhatch.xxxx should succeed for 2&3
try:
    from pyhatch.license_templates import CLASSIFIER_D
except:
    from license_templates import CLASSIFIER_D


# standard message dialogs... showinfo, showwarning, showerror
def ShowInfo(title='Title', message='your message here.'):
    """Simply wraps the tkinter function of the "same" name."""
    tkMessageBox.showinfo( title, message )
    return
def ShowWarning(title='Title', message='your message here.'):
    """Simply wraps the tkinter function of the "same" name."""
    tkMessageBox.showwarning( title, message )
    return
def ShowError(title='Title', message='your message here.'):
    """Simply wraps the tkinter function of the "same" name."""
    tkMessageBox.showerror( title, message )
    return


# standard question dialogs... askquestion, askokcancel, askyesno, or askretrycancel
# return True for OK, Yes, Retry, False for Cancel or No
def AskYesNo(title='Title', message='your question here.'):
    """Simply wraps the tkinter function of the "same" name."""
    return tkMessageBox.askyesno( title, message )
def AskOK_Cancel(title='Title', message='your question here.'):
    """Simply wraps the tkinter function of the "same" name."""
    return tkMessageBox.askokcancel( title, message )
def AskRetryCancel(title='Title', message='your question here.'):
    """Simply wraps the tkinter function of the "same" name."""
    return tkMessageBox.askretrycancel( title, message )

# return "yes" for Yes, "no" for No
def AskQuestion(title='Title', message='your question here.'):
    """Simply wraps the tkinter function of the "same" name."""
    return tkMessageBox.askquestion( title, message )
# END of standard message dialogs


class _Hatch_GUI(object):
    """
    create a Hatch object from
    hatch_supt and to then create a skeleton python project.
    """
    def __init__(self, master):
        self.initComplete = 0
        self.master = master
        self.x, self.y, self.w, self.h = -1,-1,-1,-1

        # bind master to <Configure> in order to handle any resizing, etc.
        # postpone self.master.bind("<Configure>", self.Master_Configure)
        self.master.bind('<Enter>', self.bindConfigure)

        self.master.title("empty_main")
        self.master.resizable(0,0) # Linux may not respect this

        dialogframe = Frame(master, width=819, height=860)
        dialogframe.pack()

        self.Shortdesc_Labelframe = LabelFrame(dialogframe,
                                               text="Short Description (1-liner)",
                                               height="90", width="718")
        self.Shortdesc_Labelframe.place(x=60, y=180)

        helv20 = tkFont.Font(family='Helvetica', size=20, weight='bold')

        self.Buildproject_Button = Button(dialogframe,text="Build Project",
                                          width="15", font=helv20)
        self.Buildproject_Button.place(x=492, y=24, width=263, height=68)
        self.Buildproject_Button.bind("<ButtonRelease-1>",
                                      self.Buildproject_Button_Click)

        self.Selectdir_Button = Button(dialogframe,text="<Select Directory>",
                                       width="15")
        self.Selectdir_Button.place(x=72, y=792, width=672, height=31)
        self.Selectdir_Button.bind("<ButtonRelease-1>",
                                   self.Selectdir_Button_Click)

        self.Author_Entry = Entry(dialogframe,width="15")
        self.Author_Entry.place(x=228, y=576, width=187, height=21)
        self.Author_Entry_StringVar = StringVar()
        self.Author_Entry.configure(textvariable=self.Author_Entry_StringVar)
        self.Author_Entry_StringVar.set("John Doe")

        self.Classname_Entry = Entry(dialogframe,width="15")
        self.Classname_Entry.place(x=192, y=108, width=165, height=21)
        self.Classname_Entry_StringVar = StringVar()
        self.Classname_Entry.configure(textvariable=self.Classname_Entry_StringVar)
        self.Classname_Entry_StringVar.set("MyClass")

        self.Copyright_Entry = Entry(dialogframe,width="15")
        self.Copyright_Entry.place(x=228, y=648, width=461, height=21)
        self.Copyright_Entry_StringVar = StringVar()
        self.Copyright_Entry.configure(textvariable=self.Copyright_Entry_StringVar)
        self.Copyright_Entry_StringVar.set("Copyright (c) 2013 John Doe")

        self.Email_Entry = Entry(dialogframe,relief="sunken", width="15")
        self.Email_Entry.place(x=228, y=684, width=458, height=21)
        self.Email_Entry_StringVar = StringVar()
        self.Email_Entry.configure(textvariable=self.Email_Entry_StringVar)
        self.Email_Entry_StringVar.set("johndoe@happypond.org")

        self.GithubUserName_Entry = Entry(dialogframe,relief="sunken", width="15")
        self.GithubUserName_Entry.place(x=228, y=730, width=458, height=21)
        self.GithubUserName_Entry_StringVar = StringVar()
        self.GithubUserName_Entry.configure(textvariable=self.GithubUserName_Entry_StringVar)
        self.GithubUserName_Entry_StringVar.set("github_user_name")

        self.Funcname_Entry = Entry(dialogframe,width="15")
        self.Funcname_Entry.place(x=192, y=144, width=157, height=21)
        self.Funcname_Entry_StringVar = StringVar()
        self.Funcname_Entry.configure(textvariable=self.Funcname_Entry_StringVar)
        self.Funcname_Entry_StringVar.set("my_function")

        # License values should be correct format
        LICENSE_OPTIONS = tuple( sorted(CLASSIFIER_D.keys()) )
        self.License_Entry_StringVar = StringVar()
        self.License_Entry = OptionMenu(dialogframe, self.License_Entry_StringVar, *LICENSE_OPTIONS)
        self.License_Entry.place(x=552, y=576, width=184, height=21)
        self.License_Entry_StringVar.set( LICENSE_OPTIONS[0] )

        self.Mainpyname_Entry = Entry(dialogframe,width="15")
        self.Mainpyname_Entry.place(x=168, y=60, width=196, height=21)
        self.Mainpyname_Entry_StringVar = StringVar()
        self.Mainpyname_Entry.configure(textvariable=self.Mainpyname_Entry_StringVar)
        self.Mainpyname_Entry_StringVar.set("main.py")

        self.Projname_Entry = Entry(dialogframe,width="15")
        self.Projname_Entry.place(x=168, y=24, width=194, height=21)
        self.Projname_Entry_StringVar = StringVar()
        self.Projname_Entry.configure(textvariable=self.Projname_Entry_StringVar)
        self.Projname_Entry_StringVar.set("MyProject")

        self.Shortdesc_Entry = Entry(dialogframe,width="15")
        self.Shortdesc_Entry.place(x=72, y=204, width=688, height=48)
        self.Shortdesc_Entry_StringVar = StringVar()
        self.Shortdesc_Entry.configure(textvariable=self.Shortdesc_Entry_StringVar)
        self.Shortdesc_Entry_StringVar.set("My project does this")

        # Status must be correct format
        self.Status_Entry_StringVar = StringVar()
        self.Status_Entry = OptionMenu(dialogframe, self.Status_Entry_StringVar, *DEV_STATUS_OPTIONS)
        self.Status_Entry.place(x=228, y=612, width=183, height=21)
        self.Status_Entry_StringVar.set(DEV_STATUS_OPTIONS[0])

        self.Version_Entry = Entry(dialogframe,width="15")
        self.Version_Entry.place(x=552, y=612, width=184, height=21)
        self.Version_Entry_StringVar = StringVar()
        self.Version_Entry.configure(textvariable=self.Version_Entry_StringVar)
        self.Version_Entry_StringVar.set("0.1.1")

        self.Author_Label = Label(dialogframe,text="Author", width="15")
        self.Author_Label.place(x=96, y=576, width=112, height=22)

        self.Classname_Label = Label(dialogframe,text="Class Name", width="15")
        self.Classname_Label.place(x=60, y=108, width=112, height=22)

        self.Copyright_Label = Label(dialogframe,text="Copyright", width="15")
        self.Copyright_Label.place(x=96, y=648, width=113, height=23)

        self.Email_Label = Label(dialogframe,text="Email", width="15")
        self.Email_Label.place(x=96, y=684, width=113, height=23)

        self.GithubUserName_Label = Label(dialogframe,text="GithubUserName", width="15")
        self.GithubUserName_Label.place(x=96, y=730, width=113, height=23)

        self.Funcname_Label = Label(dialogframe,text="Function Name", width="15")
        self.Funcname_Label.place(x=60, y=144, width=112, height=22)

        self.License_Label = Label(dialogframe,text="License", width="15")
        self.License_Label.place(x=432, y=576, width=113, height=23)

        self.Longdesc_Label = Label(dialogframe,text="Paragraph Description", width="15")
        self.Longdesc_Label.place(x=216, y=288, width=376, height=22)

        self.Mainpyname_Label = Label(dialogframe,text="Main Python File", width="15")
        self.Mainpyname_Label.place(x=48, y=60, width=112, height=22)

        self.Projname_Label = Label(dialogframe,text="Project Name", width="15")
        self.Projname_Label.place(x=48, y=24, width=112, height=22)

        self.Selectdir_Label = Label(dialogframe,
                                     text="Select the Directory Below Which to Place Your Project",
                                     width="15")
        self.Selectdir_Label.place(x=156, y=768, width=536, height=24)

        self.Status_Label = Label(dialogframe,text="Status", width="15")
        self.Status_Label.place(x=96, y=612, width=114, height=24)

        self.Version_Label = Label(dialogframe,text="Version", width="15")
        self.Version_Label.place(x=432, y=612, width=113, height=23)

        self.Isclass_Radiobutton = Radiobutton(dialogframe,
                                               text="Class Project",
                                               value="Class Project",
                                               width="15", anchor=W)
        self.Isclass_Radiobutton.place(x=320, y=108, width=135, height=27)
        self.RadioGroup1_StringVar = StringVar()
        self.RadioGroup1_StringVar.set("Class Project")
        self.RadioGroup1_StringVar_traceName = \
            self.RadioGroup1_StringVar.trace_variable("w",
                                                      self.RadioGroup1_StringVar_Callback)
        self.Isclass_Radiobutton.configure(variable=self.RadioGroup1_StringVar )

        self.Isfunction_Radiobutton = Radiobutton(dialogframe,text="Function Project",
                                                  value="Function Project",
                                                  width="15", anchor=W)
        self.Isfunction_Radiobutton.place(x=320, y=144, width=135, height=27)
        self.Isfunction_Radiobutton.configure(variable=self.RadioGroup1_StringVar )


        lbframe = Frame( dialogframe )
        self.Text_1_frame = lbframe
        scrollbar = Scrollbar(lbframe, orient=VERTICAL)
        self.Text_1 = Text(lbframe, width="40", height="12", yscrollcommand=scrollbar.set)
        scrollbar.config(command=self.Text_1.yview)
        scrollbar.pack(side=RIGHT, fill=Y)
        self.Text_1.pack(side=LEFT, fill=BOTH, expand=1)

        self.Text_1_frame.place(x=72, y=312, width=665, height=237)
        # >>>>>>insert any user code below this comment for section "top_of_init"

        self.dirname = '<Select Directory>'
        self.Funcname_Entry.config(state=DISABLED)

        h =  Hatch(projName='MyProject', mainDefinesClass='N')
        if h.author:
            self.Author_Entry_StringVar.set(h.author)
        if h.proj_license:
            self.License_Entry_StringVar.set(h.proj_license)
        if h.proj_copyright:
            self.Copyright_Entry_StringVar.set(h.proj_copyright)
        if h.email:
            self.Email_Entry_StringVar.set(h.email)
        if h.github_user_name:
            self.GithubUserName_Entry_StringVar.set(h.github_user_name)
        del h


    def build_result_dict(self):
        """Takes user inputs from GUI and builds a dictionary of results"""
        # pylint: disable=W0201
        self.result = {} # return a dictionary of results

        self.result["author"] = self.Author_Entry_StringVar.get()
        self.result["status"] = self.Status_Entry_StringVar.get()
        self.result["proj_license"] = self.License_Entry_StringVar.get()
        self.result["version"] = self.Version_Entry_StringVar.get()
        self.result["proj_copyright"] = self.Copyright_Entry_StringVar.get()
        self.result["email"] = self.Email_Entry_StringVar.get()
        self.result["github_user_name"] = self.GithubUserName_Entry_StringVar.get()

        self.result["main_py_name"] = self.Mainpyname_Entry_StringVar.get()
        self.result["proj_name"] = self.Projname_Entry_StringVar.get()
        self.result["class_name"] = self.Classname_Entry_StringVar.get()
        self.result["func_name"] = self.Funcname_Entry_StringVar.get()

        self.result["short_desc"] = self.Shortdesc_Entry_StringVar.get()
        self.result["para_desc"] = self.Text_1.get(1.0, END)
        self.result["parent_dir"] = self.dirname

        if self.RadioGroup1_StringVar.get() == "Class Project":
            self.result["is_class_project"] = 'Y'
        else:
            self.result["is_class_project"] = 'N'


    def Buildproject_Button_Click(self, event):
        """When clicked, this method gathers all the user inputs
            and builds the project skeleton in the directory specified.
        """


        #  tkinter requires arguments, but I don't use them
        # pylint: disable=W0613

        # >>>>>>insert any user code below this comment for section "compID=29"
        # replace, delete, or comment-out the following
        #print "executed method Buildproject_Button_Click"

        if not os.path.isdir( self.dirname ):
            ShowError(title='Need Parent Directory',
                      message='You need to choose a directory in which to place your project.')
        else:
            self.build_result_dict() # builds self.result dict
            r = self.result

            h =  Hatch(projName=r["proj_name"], mainDefinesClass=r["is_class_project"],
                       mainPyFileName=r["main_py_name"],
                       mainClassName=r["class_name"], mainFunctionName=r["func_name"],
                       author=r["author"], proj_copyright=r["proj_copyright"],
                       proj_license=r["proj_license"], version=r["version"],
                       email=r["email"], status=r["status"], github_user_name=r["github_user_name"],
                       simpleDesc=r["short_desc"],
                       longDesc=r["para_desc"])

            call_result = h.save_project_below_this_dir( self.dirname )
            if call_result=='Success':
                if AskYesNo(title='Exit Dialog', message='Do you want to leave this GUI?'):
                    self.master.destroy()
            else:
                ShowWarning( title='Project Build Error',
                             message='Project did NOT build properly.\n'+\
                            'Warning Message = (%s)'%call_result)


    # return a string containing directory name
    def AskDirectory(self, title='Choose Directory', initialdir="."):
        """Simply wraps the tkinter function of the "same" name."""
        dirname = tkFileDialog.askdirectory(parent=self.master,initialdir=initialdir,title=title)
        return dirname # <-- string


    def Selectdir_Button_Click(self, event):
        #  I don't care what the exception is, if there's a problem, bail
        #     Also, I want to redefine the dirname attribute here
        # pylint: disable=W0702, W0201

        #  tkinter requires arguments, but I don't use them
        # pylint: disable=W0613

        """Selects the directory in which to build project."""

        dirname = self.AskDirectory( title='Choose Directory For Nose Tests', initialdir='.')
        if dirname:
            try:
                dirname = os.path.abspath( dirname )
            except:
                self.dirname = '<Select Directory>'
                return # let Alarm force dir selection

            self.dirname = dirname

            self.Selectdir_Button.config(text=self.dirname)


    def RadioGroup1_StringVar_Callback(self, varName, index, mode):
        #  tkinter requires arguments, but I don't use them
        # pylint: disable=W0613

        """Responds to changes in RadioGroup1_StringVar."""
        if self.RadioGroup1_StringVar.get() == "Class Project":
            self.Funcname_Entry.config(state=DISABLED)
            self.Classname_Entry.config(state=NORMAL)
        else:
            self.Classname_Entry.config(state=DISABLED)
            self.Funcname_Entry.config(state=NORMAL)



    # tk_happy generated code. DO NOT EDIT THE FOLLOWING. section "Master_Configure"
    def bindConfigure(self, event):
        """bindConfigure and Master_Configure help stabilize GUI"""
        #  tkinter requires arguments, but I don't use them
        # pylint: disable=W0613
        if not self.initComplete:
            self.master.bind("<Configure>", self.Master_Configure)
            self.initComplete = 1


    def Master_Configure(self, event):
        """bindConfigure and Master_Configure help stabilize GUI"""
        # >>>>>>insert any user code below this comment for section "Master_Configure"
        # replace, delete, or comment-out the following
        if event.widget != self.master:
            if self.w != -1:
                return
        x = int(self.master.winfo_x())
        y = int(self.master.winfo_y())
        w = int(self.master.winfo_width())
        h = int(self.master.winfo_height())
        if (self.x, self.y, self.w, self.h) == (-1,-1,-1,-1):
            self.x, self.y, self.w, self.h = x,y,w,h


        if self.w!=w or self.h!=h:
            print "Master reconfigured... make resize adjustments"
            self.w=w
            self.h=h
# tk_happy generated code. DO NOT EDIT THE FOLLOWING. section "end"

def main():
    """Run the GUI"""
    root = Tk()
    _Hatch_GUI(root)
    root.mainloop()

if __name__ == '__main__':
    main()
